import {IComputer} from "../../redux/types/computerTypes";

const computersData: IComputer[] = [
  {
    id: 1,
    name: 'Компьютер 1',
    cpu: 'Intel Core i3 11400',
    gpu: 'GeForce GTX 1050',
    ram: '2gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 2,
    name: 'Компьютер 2',
    cpu: 'Intel Core i3 11400',
    gpu: 'GeForce GTX 1050',
    ram: '2gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 3,
    name: 'Компьютер 3',
    cpu: 'Intel Core i3 11400',
    gpu: 'GeForce GTX 1050',
    ram: '2gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 4,
    name: 'Компьютер 4',
    cpu: 'Intel Core i5 11400',
    gpu: 'GeForce GTX 1060',
    ram: '4gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 5,
    name: 'Компьютер 5',
    cpu: 'Intel Core i5 11400',
    gpu: 'GeForce GTX 1060',
    ram: '4gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 6,
    name: 'Компьютер 6',
    cpu: 'Intel Core i5 11400',
    gpu: 'GeForce GTX 1060',
    ram: '4gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 7,
    name: 'Компьютер 7',
    cpu: 'Intel Core i5 11400',
    gpu: 'GeForce GTX 1080',
    ram: '8gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 8,
    name: 'Компьютер 8',
    cpu: 'Intel Core i5 11400',
    gpu: 'GeForce GTX 1080',
    ram: '8gb',
    storage: '512gb',
    monitor: '1080x720',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 9,
    name: 'Компьютер 9',
    cpu: 'Intel Core i7 11400',
    gpu: 'GeForce RTX 3060',
    ram: '16gb',
    storage: '512gb',
    monitor: '1920x1080',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 10,
    name: 'Компьютер 10',
    cpu: 'Intel Core i7 11400',
    gpu: 'GeForce RTX 3070',
    ram: '32gb',
    storage: '512gb',
    monitor: '1920x1080',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
  {
    id: 11,
    name: 'Компьютер 11',
    cpu: 'Intel Core i9 11400',
    gpu: 'GeForce GTX 3090',
    ram: '64gb',
    storage: '2tb',
    monitor: '3840x2160',
    mouse: 'razer',
    keypad: 'razer',
    earphones: 'razer',
    webcamera: 'razer'
  },
]

export default computersData;